import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowDownToLine, ArrowRight, AudioLines, CalendarDays, ChevronRight, Clock3, FileText, FolderOpen, HardDrive, Menu, Mic, Plus, Search, Settings2, ShieldCheck, Sparkles, Upload, Users, X } from 'lucide-react'
import { BrandMark, Feedback, PrivacyBadge, Spinner } from './components'
import MeetingWorkspace from './MeetingWorkspace'
import RecordingModal from './RecordingModal'
import SettingsPanel from './SettingsPanel'
import { api, busy, dateLabel, duration, speechReady } from './types'
import type { Meeting, Settings } from './types'

export default function App() {
  const [meetings, setMeetings] = useState<Meeting[]>([])
  const [settings, setSettings] = useState<Settings | null>(null)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [page, setPage] = useState<'meetings' | 'settings'>('meetings')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [search, setSearch] = useState('')
  const [capture, setCapture] = useState<'record' | 'import' | null>(null)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const mutationVersion = useRef(0)
  const refreshVersion = useRef(0)
  const refresh = useCallback(async () => {
    const version = mutationVersion.current
    const request = ++refreshVersion.current
    const results = await Promise.allSettled([api<Meeting[]>('/meetings'), api<Settings>('/settings')])
    if (request !== refreshVersion.current) return
    if (results[0].status === 'fulfilled' && version === mutationVersion.current) setMeetings(previous => results[0].status === 'fulfilled' ? results[0].value.map(incoming => { const current = previous.find(item => item.id === incoming.id); return current && current.updated_at > incoming.updated_at ? current : incoming }) : previous)
    if (results[1].status === 'fulfilled' && version === mutationVersion.current) setSettings(results[1].value)
    const failed = results.find(result => result.status === 'rejected') as PromiseRejectedResult | undefined
    if (failed) setError((failed.reason as Error).message)
    else setError(null)
    setLoading(false)
  }, [])
  useEffect(() => { void refresh(); const interval = setInterval(() => { if (!document.hidden) void refresh() }, 3500); return () => clearInterval(interval) }, [refresh])
  function update(meeting: Meeting) { mutationVersion.current += 1; setMeetings(previous => [meeting, ...previous.filter(item => item.id !== meeting.id)].sort((a, b) => b.created_at.localeCompare(a.created_at))) }
  function navigate(id: string | null) { setSelectedId(id); setPage('meetings'); setSidebarOpen(false) }
  function showSettings() { setPage('settings'); setSidebarOpen(false) }
  const selected = meetings.find(meeting => meeting.id === selectedId)
  const ready = speechReady(settings?.speech)
  const filtered = meetings.filter(meeting => `${meeting.title} ${meeting.segments.map(segment => segment.text).join(' ')}`.toLowerCase().includes(search.toLowerCase()))
  const totalMinutes = Math.round(meetings.reduce((total, meeting) => total + meeting.duration, 0) / 60)
  return <div className="app-shell">
    {sidebarOpen && <button className="sidebar-scrim" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}
    <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><button className="brand" onClick={() => navigate(null)} aria-label="Stillnote home"><BrandMark /><span>stillnote<span className="brand-period">.</span></span></button><p className="brand-tagline">A little room to listen.</p><button className="button primary new-recording" onClick={() => { setCapture('record'); setSidebarOpen(false) }}><Plus size={18} />New recording</button><nav className="main-nav" aria-label="Main navigation"><button className={page === 'meetings' && !selectedId ? 'active' : ''} onClick={() => navigate(null)}><FolderOpen size={18} />All meetings<span className="nav-count">{meetings.length}</span></button><button className={page === 'settings' ? 'active' : ''} onClick={showSettings}><Settings2 size={18} />Settings</button></nav><div className="sidebar-recent"><p className="nav-label">RECENT MEETINGS</p>{meetings.length ? meetings.slice(0, 6).map(meeting => <button className={`recent-meeting ${selectedId === meeting.id && page === 'meetings' ? 'selected' : ''}`} key={meeting.id} onClick={() => navigate(meeting.id)}>{busy(meeting) ? <Spinner size={15} /> : <AudioLines size={16} />}<span>{meeting.title}<small>{new Date(meeting.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</small></span></button>) : <div className="recent-empty"><span>Your next good conversation<br />belongs right here.</span><svg viewBox="0 0 95 65" fill="none" aria-hidden="true"><path d="M13 12c27 1 15 40 42 33 26-7 21-23 3-16-14 6 2 25 24 25M72 47l11 7-12 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg></div>}</div><div className="sidebar-bottom"><div className="private-card"><span><ShieldCheck size={19} /></span><strong>Your words stay yours.</strong><p>Record and transcribe locally.<br />Share only when you choose.</p><div><span className="status-dot" />{settings?.speech.installing ? 'Setting up local models' : ready ? 'Local engine ready' : 'A private, local workspace'}</div></div><div className="workspace-label"><span className="workspace-avatar"><HardDrive size={14} /><span /></span><span>Personal workspace<small>Stored on this computer</small></span><HardDrive size={14} /></div></div></aside>
    <main className="main-shell"><header className="topbar"><div><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setSidebarOpen(true)}><Menu size={21} /></button><span className="breadcrumb-root">Workspace</span><ChevronRight size={13} /><span>{page === 'settings' ? 'Settings' : selected ? selected.title : 'All meetings'}</span></div><PrivacyBadge compact /></header><div className="main-content">
    {error && <div className="connection-error"><Feedback error={error} /><button className="text-button" onClick={() => void refresh()}>Try again</button><button className="icon-button" aria-label="Dismiss connection message" onClick={() => setError(null)}><X size={15} /></button></div>}
    {page === 'settings' ? settings ? <SettingsPanel settings={settings} onSave={next => { mutationVersion.current += 1; setSettings(next) }} onBack={() => navigate(selectedId)} onRefresh={refresh} /> : <div className="loading-state"><Spinner size={22} /><p>{loading ? 'Loading your preferences…' : 'Connect to the local server to manage preferences.'}</p></div> : selected ? <MeetingWorkspace key={selected.id} meeting={selected} settings={settings} onUpdate={update} onDelete={id => { mutationVersion.current += 1; setMeetings(previous => previous.filter(item => item.id !== id)); setSelectedId(null) }} onBack={() => navigate(null)} onSettings={showSettings} /> : <div className="home-page page-enter">
      <div className="page-heading"><div><p className="eyebrow">LESS NOTE-TAKING. MORE BEING HERE.</p><h1>Your space to listen.</h1><p>Good conversations deserve to be remembered.</p></div><span className="today-date"><CalendarDays size={15} />{new Date().toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</span></div>
      <section className="welcome-card"><div className="welcome-copy"><span className="welcome-label"><span />BE PRESENT. WE’LL REMEMBER.</span><h2>Big ideas start with<br />a little listening.</h2><p>Record the conversation. Find every voice.<br />Keep what matters — all in your own space.</p><div className="button-row"><button className="button primary" onClick={() => setCapture('record')}><Mic size={17} />Record a meeting</button><button className="button hero-secondary" onClick={() => setCapture('import')}><Upload size={16} />Import audio</button></div><div className="welcome-footnote"><ShieldCheck size={13} />Recording & transcription never leave your device</div></div><div className="welcome-art" aria-hidden="true"><div className="art-ring ring-one" /><div className="art-ring ring-two" /><div className="art-ring ring-three" /><div className="art-paper"><span className="paper-dot" /><span className="paper-line long" /><span className="paper-line" /><span className="paper-line short" /><div className="paper-wave">{[11, 20, 32, 18, 39, 53, 36, 20, 28, 46, 29, 14, 22, 11].map((value, i) => <span key={i} style={{ height: value }} />)}</div><div className="paper-bottom"><span /><i /><i /></div></div><div className="art-speaker"><Users size={18} /><span>Every voice matters</span></div><div className="art-sparkle">✳</div><span className="art-label">a thought worth keeping</span><svg className="art-arrow" viewBox="0 0 90 55" fill="none"><path d="M5 6c20-10 51 6 48 21-3 14-24-4-8-10 14-6 22 12 25 28M60 39l10 8 6-12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg></div></section>
      <div className="feature-strip"><div><span className="feature-icon"><Mic size={18} /></span><span><strong>Capture naturally</strong><small>Record or bring your own audio</small></span></div><div><span className="feature-icon sage"><Users size={18} /></span><span><strong>Know who said what</strong><small>Local multi-speaker transcription</small></span></div><div><span className="feature-icon lavender"><Sparkles size={18} /></span><span><strong>Leave with clarity</strong><small>Key points, decisions & next steps</small></span></div></div>
      {!loading && !ready && <div className="setup-banner"><span className="setup-banner-icon">{settings?.speech.installing ? <Spinner size={19} /> : <ArrowDownToLine size={19} />}</span><div><strong>{settings?.speech.installing ? 'Your local workspace is getting ready.' : 'A one-time setup. A little more peace of mind.'}</strong><p>{settings?.speech.installing ? settings.speech.detail || 'Downloading local speech models. Your recordings stay on this device.' : 'Download local speech models to unlock transcription and speaker detection.'}</p></div><button className="text-button" onClick={showSettings}>{settings?.speech.installing ? 'View progress' : 'Set up models'}<ArrowRight size={16} /></button></div>}
      <section className="meetings-section"><div className="section-heading"><div><h2>Your meetings<span>{meetings.length}</span></h2><p>{meetings.length ? `${totalMinutes > 0 ? `${totalMinutes} minute${totalMinutes === 1 ? '' : 's'} captured. ` : ''}Room for every conversation.` : 'All your conversations, thoughtfully organized.'}</p></div><label className="meeting-search"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search meetings…" aria-label="Search meetings" />{search && <button className="icon-button" aria-label="Clear meeting search" onClick={() => setSearch('')}><X size={13} /></button>}</label></div>
      {loading ? <div className="loading-state"><Spinner size={24} /><p>Opening your workspace…</p></div> : !meetings.length ? <div className="meetings-empty"><div className="empty-illustration"><div className="empty-paper"><AudioLines size={29} strokeWidth={1.2} /><i /><i /></div><span className="empty-orbit" /><span className="empty-dot" /></div><h3>Your first conversation starts here.</h3><p>A team catch-up, a bright idea, a conversation worth keeping.<br />Hit record and make a little room to listen.</p><button className="text-button" onClick={() => setCapture('record')}>Record your first meeting<ArrowRight size={16} /></button><span className="empty-local"><HardDrive size={12} />Saved on your device. Always within reach.</span></div> : filtered.length ? <div className="meeting-list"><div className="meeting-list-labels"><span>MEETING</span><span>DATE</span><span>DURATION</span><span>STATUS</span></div>{filtered.map(meeting => <button className="meeting-list-row" onClick={() => navigate(meeting.id)} key={meeting.id}><div className="meeting-row-title"><span className={`meeting-file-icon ${meeting.summary ? 'has-summary' : ''}`}>{busy(meeting) ? <Spinner size={19} /> : <FileText size={20} strokeWidth={1.5} />}</span><span><strong>{meeting.title}</strong><small>{Object.keys(meeting.speakers).length ? `${Object.keys(meeting.speakers).length} speakers · ` : ''}{meeting.summary ? 'Summary ready' : meeting.segments.length ? 'Transcript ready' : 'Recording saved'}</small></span></div><span className="row-date">{dateLabel(meeting.created_at)}</span><span className="row-duration"><Clock3 size={13} />{meeting.duration > 0 ? duration(meeting.duration) : '—'}</span><span className={`status-pill ${meeting.status === 'complete' ? 'green' : meeting.status === 'error' ? 'red' : ''}`}>{meeting.status === 'transcribing' ? 'Transcribing' : meeting.status === 'summarizing' ? 'Summarizing' : meeting.status === 'complete' ? 'Complete' : meeting.status === 'transcribed' ? 'Transcribed' : meeting.status === 'error' ? 'Needs attention' : 'Recorded'}</span><ChevronRight className="meeting-row-arrow" size={16} /></button>)}</div> : <div className="search-empty"><Search size={28} /><h3>No meetings found</h3><p>Try another title or a word from the conversation.</p><button className="text-button" onClick={() => setSearch('')}>Clear search</button></div>}
      </section><footer className="home-footer"><span>Made for the moments that matter.</span><span><ShieldCheck size={13} />Local first. Yours always.</span></footer>
    </div>}
    </div></main>
    {capture && <RecordingModal mode={capture} settings={settings} onClose={() => setCapture(null)} onSaved={meeting => { update(meeting); setCapture(null); navigate(meeting.id) }} />}
  </div>
}
